ci: do not update package-lock to dev/main

diff --git a/.github/workflows/run_dev_tests.yml b/.github/workflows/run_dev_tests.yml
--- a/.github/workflows/run_dev_tests.yml
+++ b/.github/workflows/run_dev_tests.yml
@@ -21,11 +21,16 @@ jobs:
       run: |
         npm install
         if [[ `git status --porcelain` ]]; then
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add package-lock.json
-          git commit -m 'Update package-lock.json'
-          git push origin HEAD:${GITHUB_HEAD_REF}
+          if [[ "${GITHUB_HEAD_REF}" == "dev" || "${GITHUB_HEAD_REF}" == "main" ]]; then
+            echo "Error: package-lock.json is outdated but cannot auto-commit to ${GITHUB_HEAD_REF}. Please review and commit the changes."
+            git diff
+            exit 1
+          else:
+            git config --global user.name 'github-actions[bot]'
+            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+            git add package-lock.json
+            git commit -m 'Update package-lock.json'
+            git push origin HEAD:${GITHUB_HEAD_REF}
         else
           echo "No changes in package-lock.json"
         fi
diff --git a/.github/workflows/run_main_tests.yml b/.github/workflows/run_main_tests.yml
--- a/.github/workflows/run_main_tests.yml
+++ b/.github/workflows/run_main_tests.yml
@@ -18,13 +18,20 @@ jobs:
       uses: actions/setup-node@v3
       with:
         node-version: "16.x"
-    - name: Check package-lock
+    - name: Update package-lock
       run: |
         npm install
         if [[ `git status --porcelain` ]]; then
-          echo "Error: package-lock.json has changed. Please review and commit the changes."
-          git diff
-          exit 1
+          if [[ "${GITHUB_HEAD_REF}" == "dev" || "${GITHUB_HEAD_REF}" == "main" ]]; then
+            echo "Error: package-lock.json is outdated but cannot auto-commit to ${GITHUB_HEAD_REF}. Please review and commit the changes."
+            git diff
+            exit 1
+          else:
+            git config --global user.name 'github-actions[bot]'
+            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+            git add package-lock.json
+            git commit -m 'Update package-lock.json'
+            git push origin HEAD:${GITHUB_HEAD_REF}
         else
           echo "No changes in package-lock.json"
         fi
